server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://100.89.209.81:3100/loki/api/v1/push

scrape_configs:
  # üîê SSH Honeypot (Cowrie)
  - job_name: cowrie
    static_configs:
      - targets: [localhost]
        labels:
          job: cowrie
          service: ssh
          host: vm1
          __path__: /home/cstc/honeypot-project/cowrie/data/cowrie.json 

  # üåê HTTP Honeypot - EXACT FILENAME ONLY
  - job_name: web
    static_configs:
      - targets: [localhost]
        labels:
          job: web
          service: http
          host: vm1
          __path__: /home/cstc/honeypot-project/http_honeypot/data/honeypot.log


  # üìÅ FTP Honeypot
  - job_name: ftp
    static_configs:
      - targets: [localhost]
        labels:
          job: ftp
          service: ftp
          host: vm1
          __path__: /home/cstc/honeypot-project/ftp_h/logs/syslog


  # üóÑ MySQL Honeypot
  - job_name: mysql
    static_configs:
      - targets: [localhost]
        labels:
          job: mysql
          service: mysql
          host: vm1
          __path__: /home/cstc/honeypot-project/sql-h/log/mysql.log
